sudo: required
services:
  - docker:

before_install:
  - docker build -t safaa1001/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true safaa1001/react-app npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react3"
  env: "DockerReact3-env"
  bucket_name: "elasticbeanstalk-eu-west-1-410896695229"
  bucket_path: "docker-react3"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY #local env in travis ci
  secret_access_key:
    secure: "AWS_SECRET_KEY" #local env in travis ci