version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis-server:
    image: 'redis:latest'
  nginx:
    restart: always
    stdin_open: true
    tty: true
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: #map local port
      - '3050:80'
  api:
    stdin_open: true
    tty: true
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app/server
    environment: # those are setup once on runtime level and not on image level
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
      - PGPORT=5432
  worker:
    stdin_open: true
    tty: true
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
  client:
    stdin_open: true
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app